name: publish packages
on:
  push:
    branches:
      - release_v1.1.1
  pull_request:
    branches: 
      - release_v1.1.1
jobs:
  publish:
    permissions: 
      contents: read
      packages: write
    runs-on: ubuntu-latest 
    if: ${{ github.ref == 'refs/heads/release_v1.1.1' }}
    steps:

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: release_v1.1.1
          lfs: true

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish package
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
